'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useQueryClient } from '@tanstack/react-query';
import { api, ApiError } from '@/lib/api';
import { useTranslation } from '@/lib/i18n';
import type { Community } from '@zktalk/shared';
import type { CommunityVisibility } from '@zktalk/shared';

function slugify(name: string): string {
  const base = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
  // Non-ASCII names (e.g. Korean) produce empty base — generate a unique slug
  return base || `community-${Math.random().toString(36).slice(2, 8)}`;
}

type SlugFeedback = 'idle' | 'auto' | 'converted' | 'needsManual';

export default function NewCommunityPage() {
  const router = useRouter();
  const queryClient = useQueryClient();
  const { t } = useTranslation();
  const [name, setName] = useState('');
  const [slug, setSlug] = useState('');
  const [slugEdited, setSlugEdited] = useState(false);
  const [slugFeedback, setSlugFeedback] = useState<SlugFeedback>('idle');
  const [description, setDescription] = useState('');
  const [visibility, setVisibility] = useState<CommunityVisibility>('public');
  const [error, setError] = useState<string | null>(null);
  const [isSubmitting, setIsSubmitting] = useState(false);

  function handleNameChange(value: string) {
    setName(value);
    if (!slugEdited) {
      const generatedSlug = slugify(value);
      setSlug(generatedSlug);
      if (!value.trim()) {
        setSlugFeedback('idle');
      } else if (generatedSlug) {
        setSlugFeedback('auto');
      } else {
        setSlugFeedback('needsManual');
      }
    }
  }

  function handleSlugChange(value: string) {
    setSlugEdited(true);
    const sanitized = slugify(value);
    setSlug(sanitized);
    if (!value.trim()) {
      setSlugFeedback('idle');
    } else if (!sanitized) {
      setSlugFeedback('needsManual');
    } else if (sanitized !== value.trim().toLowerCase()) {
      setSlugFeedback('converted');
    } else {
      setSlugFeedback('idle');
    }
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    setError(null);
    if (!slug.trim()) {
      setError(t('community.slugRequired'));
      return;
    }
    setIsSubmitting(true);

    try {
      const res = await api<{ community: Community }>('/api/communities', {
        method: 'POST',
        body: { name, slug, description: description || undefined, visibility },
      });
      await queryClient.invalidateQueries({ queryKey: ['communities'] });
      router.push(`/communities/${res.community.slug}`);
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message);
      } else {
        setError(t('community.createError'));
      }
      setIsSubmitting(false);
    }
  }

  const slugHelpText =
    slugFeedback === 'auto' && slug
      ? t('community.slugAutoGenerated', { slug })
      : slugFeedback === 'converted' && slug
        ? t('community.slugConverted', { slug })
        : slugFeedback === 'needsManual'
          ? t('community.slugNeedsManual')
          : t('community.slugRules');

  const slugHelpTone =
    slugFeedback === 'needsManual' ? 'text-warning' : 'text-fg-muted';

  return (
    <div className="flex flex-1 flex-col">
      <header className="border-b border-line px-6 py-4 pl-14 md:pl-6">
        <h1 className="text-lg font-bold">{t('community.create')}</h1>
      </header>

      <div className="flex-1 overflow-y-auto p-6">
        <form
          onSubmit={handleSubmit}
          className="mx-auto max-w-lg space-y-5 rounded-lg bg-bg-subtle p-6"
        >
          {/* Name */}
          <div>
            <label htmlFor="name" className="mb-1 block text-sm font-medium text-fg-muted">
              {t('community.name')}
            </label>
            <input
              id="name"
              type="text"
              required
              maxLength={100}
              value={name}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder={t('community.namePlaceholder')}
              className="w-full rounded-md border border-line bg-bg-subtle px-3 py-2 text-sm text-fg-muted placeholder-gray-400 focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>

          {/* Slug */}
          <div>
            <label htmlFor="slug" className="mb-1 block text-sm font-medium text-fg-muted">
              {t('community.slug')}
            </label>
            <div className="flex items-center rounded-md border border-line bg-bg-subtle">
              <span className="px-3 text-sm text-fg-muted">{t('community.slugPrefix')}</span>
              <input
                id="slug"
                type="text"
                required
                maxLength={50}
                value={slug}
                onChange={(e) => handleSlugChange(e.target.value)}
                className="w-full bg-transparent px-1 py-2 text-sm text-fg-muted focus:outline-none"
              />
            </div>
            <p className={`mt-2 text-xs ${slugHelpTone}`}>
              {slugHelpText}
            </p>
          </div>

          {/* Description */}
          <div>
            <label htmlFor="description" className="mb-1 block text-sm font-medium text-fg-muted">
              {t('community.description')}
            </label>
            <textarea
              id="description"
              maxLength={500}
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder={t('community.descPlaceholder')}
              className="w-full rounded-md border border-line bg-bg-subtle px-3 py-2 text-sm text-fg-muted placeholder-gray-400 focus:border-accent focus:outline-none focus:ring-1 focus:ring-accent"
            />
          </div>

          {/* Visibility */}
          <div>
            <label className="mb-2 block text-sm font-medium text-fg-muted">
              {t('community.visibility')}
            </label>
            <div className="space-y-2">
              {([
                { value: 'public', label: t('community.public'), desc: t('community.publicDesc') },
                { value: 'invite_only', label: t('community.inviteOnly'), desc: t('community.inviteOnlyDesc') },
                { value: 'private', label: t('community.private'), desc: t('community.privateDesc') },
              ] as const).map((opt) => (
                <label
                  key={opt.value}
                  className={`flex cursor-pointer items-start gap-3 rounded-md border p-3 transition-colors ${
                    visibility === opt.value
                      ? 'border-accent bg-accent/10'
                      : 'border-line hover:border-line'
                  }`}
                >
                  <input
                    type="radio"
                    name="visibility"
                    value={opt.value}
                    checked={visibility === opt.value}
                    onChange={() => setVisibility(opt.value)}
                    className="mt-0.5"
                  />
                  <div>
                    <div className="text-sm font-medium">{opt.label}</div>
                    <div className="text-xs text-fg-muted">{opt.desc}</div>
                  </div>
                </label>
              ))}
            </div>
          </div>

          {error && <p className="text-sm text-danger">{error}</p>}

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => router.back()}
              className="rounded-md border border-line px-4 py-2 text-sm font-medium text-fg-muted transition-colors hover:bg-bg-subtle"
            >
              {t('common.cancel')}
            </button>
            <button
              type="submit"
              disabled={isSubmitting || !name.trim() || !slug.trim()}
              className="rounded-md bg-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-accent disabled:opacity-50"
            >
              {isSubmitting ? t('community.creating') : t('community.createBtn')}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
